#参照ruicky/jd_sign_bot

name: 多看点自动刷金币
on:
    push:
        branches:
            - master
    schedule:
        - cron: '0,30 7-11 * * *'
    watch:
      types: [started]

jobs:
    build:
        runs-on: ubuntu-20.04
 
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run
              run: npm install
            - run: node dkd_coin.js
              env:
                dkdurl: ${{ secrets.dkdurl }}
                dkdbody: ${{ secrets.dkdbody }}
                sckey: ${{ secrets.sckey }}
                dkdhd: ${{ secrets.dkdhd }}

            - name: Delete workflow runs
              uses: GitRML/delete-workflow-runs@main
              with:
                 keep_minimum_runs: 10
