#参照ruicky/jd_sign_bot

name: 多看点自动刷金币
on:
    push:
        branches:
            - main
    schedule:
        - cron: '8 0-12 * * *'
    watch:
      types: [started]

jobs:
    build:
        runs-on: ubuntu-20.04
 
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run
              run: npm install
            - run: node dkd_coin.js
              env:
                dkdurl: ${{ secrets.dkdurl }}
                dkdbody: ${{ secrets.dkdbody }}
                sckey: ${{ secrets.sckey }}
                dkdhd: ${{ secrets.dkdhd }}

            - name: 删除7天以外的workflow流程
              uses: Mattraks/delete-workflow-runs@main
              with:
                token: ${{ github.token }}
                repository: ${{ github.repository }} 
                #保留7天不删除
                retain_days: 7
                keep_minimum_runs: 0
