#参照ruicky/jd_sign_bot

name: 多看点自动刷金币
on:
    push:
        branches:
            - main
    schedule:
        - cron: '10 * * * *'
    watch:
      types: [started]

jobs:
    build:
        runs-on: ubuntu-20.04
 
        steps:
            - name: 取出代码
              uses: actions/checkout@v2
            - name: 检查环境
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: 正在安装环境
              run: npm install
            - run: 脚本执行中
              env:
                dkdurl: ${{ secrets.dkdurl }}
                dkdbody: ${{ secrets.dkdbody }}
                sckey: ${{ secrets.sckey }}
                dkdhd: ${{ secrets.dkdhd }}
            - name: 删除过期任务
              uses: GitRML/delete-workflow-runs@main
              with:
                 retain_days: 3
